name: CI

on:
  push:
    tags:
      - "*"

jobs:
  makepkg:
    name: "Build on Arch Linux"
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate file
        run: |
          echo $(pwd)

          echo 'github.workspace === ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"

          cd $GITHUB_WORKSPACE/dir1
          echo "hello world" > hello.txt
          echo "title=$(TZ='Asia/Shanghai' date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ${{ github.workspace }}/dir1/*.txt
          name: ${{ env.title }}
          token: ${{ secrets.GITHUB_TOKEN }}
