name: trigger


on:
  push:
    branches:
      - master
    tags:
      - "*"
  create:

jobs:
  print_event_info:
    name: trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print
        run: |
          echo github.ref=${{ github.ref }}
          echo github.event_name=${{ github.event_name }}
          echo github.event=${{ github.event }}
          echo github.event.name=${{ github.event.name }}
          echo github.event.ref=${{ github.event.ref }}
          echo github.event.ref_type=${{ github.event.ref_type }}
          event_name=${{ github.event_name }}
          echo event_name=${event_name^}
          echo "event_name=${event_name^}" >> $GITHUB_ENV

      - name: if1
        if: "contains(toJSON(github.event.ref_type), 'tag')"
        run: |
          echo "if1"

      - name: if2
        if: ${{ github.event.ref_type }} == 'tag'
        run: |
          echo "if2"
      
      - name: Print
        run: |
          echo ${{ env.event_name }}
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

